server:
  port: 8083

spring:
  application:
    name: gx-cloud-iot
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:datasource.yaml
      - optional:nacos:common.yaml

mqtt:
  brokerUrl: tcp://8.147.232.206:1883
  username: admin
  password: public
  clientId: springboot-server
  defaultTopic: iot/device/#
